-- Creating Tables in MySQL
CREATE TABLE IF NOT EXISTS employee_db.EMP_RECORDS(
EMP_ID VARCHAR(4) NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100),
GENDER VARCHAR(1),
CHECK(GENDER IN ('M','F','O'))
)ENGINE=INNODB;

-- Changing the Storage Engine of a Table
ALTER TABLE employee_db.emp_records ENGINE=MERGE;

-- CHECK Constraint in MySQL: Example
CREATE TABLE IF NOT EXISTS employee_db.EMP_TABLE_2 
(
EMP_ID VARCHAR(4) NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100),
GENDER VARCHAR(1),
ROLE VARCHAR(100),
DEPT VARCHAR(100),
MANAGER_ID VARCHAR(100),
EXP INTEGER NOT NULL CHECK (EXP >= 0)
) ENGINE=INNODB;

-- CHECK Constraint in MySQL
CREATE TABLE IF NOT EXISTS employee_db.EMP_TABLE_3 
(
EMP_ID VARCHAR(4) NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100),
GENDER VARCHAR(1),
ROLE VARCHAR(100),
DEPT VARCHAR(100),
MANAGER_ID VARCHAR(100),
EXP INTEGER NOT NULL CHECK (EXP >= 0),
CONSTRAINT Gener_check CHECK(GENDER in ('M','F','O'))
) ENGINE=INNODB;

-- Analyzing Table Description in MySQL
DESC employee_db.emp_records;

-- Listing Existing Tables in MySQL
USE employee_db;
SHOW TABLES;
